#include "parallel_dependency_index_dispenser.h"

// -- LOCAL

// .. REFERENCES

#include "counted_object.h"

// -- PUBLIC

// .. CONSTRUCTORS

PARALLEL_DEPENDENCY_INDEX_DISPENSER::PARALLEL_DEPENDENCY_INDEX_DISPENSER(
    VOID
    ) :
    COUNTED_OBJECT()
{
}

// ~~

PARALLEL_DEPENDENCY_INDEX_DISPENSER::~PARALLEL_DEPENDENCY_INDEX_DISPENSER(
    VOID
    )
{
}

PARALLEL_DEPENDENCY_INDEX_DISPENSER
    *PARALLEL_DEPENDENCY_INDEX_DISPENSER::Instance = 0;