#-------------------------------------------------------------------------------
# PlayerViz (Player Trace Visualizer) 
# Version 0.5 Released 08.10.2007
# Part of the CGUL (Common Games Understanding and Learning) Toolkit
#-------------------------------------------------------------------------------
#  Copyright (C) 2007 Priyesh N. Dixit and G. Michael Youngblood
#  Game Intelligence Group, Games + Learning Lab
#  The University of North Carolina at Charlotte
#  College of Computing and Informatics, Department of Computer Science
#  9201 University City Blvd, Charlotte, NC 28223-0001
#  {pndixit, youngbld}@uncc.edu
#-------------------------------------------------------------------------------
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#-------------------------------------------------------------------------------

UMAKEFILE=Makefile.`uname|sed 's|/|_|;s|-.*||'`

all:
	make -f $(UMAKEFILE) all

clean:
	make -f $(UMAKEFILE) clean
	
###############################  END OF FILE ###############################
